server:
  port: 16666


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.24.22.88:3306/code_review_system?characterEncoding=utf-8&useSSL=false
    username: root
    password: icesCosine2020.
    hikari:
      max-lifetime: 120000

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.euphonium.codereviewsystemserver.entity
  configuration:
    map-underscore-to-camel-case: true


